name: Package Hazelcast platform release metadata
description: Creates a draft PR for the updated release metadata, after adding the required Hazelcast platform release
run-name: ${{ github.workflow }} (`${{ inputs.VERSION }}`@${{ inputs.ENVIRONMENT }})

on:
  # Called from release pipeline
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'The version to release (e.g. `5.4.1`)'
        required: true
      RELEASE_TYPE:
        description: 'What should be built'
        required: true
        type: choice
        options:
          - ALL
          - OSS
          - EE
      ENVIRONMENT:
        description: 'Environment to use'
        required: true
        type: environment

jobs:
  package:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-slim
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        # Required to get the default branch as well, to allow `gh` to accurately determine the diff between branches when deriving PR title from commits 
        with:
          fetch-depth: 0

      - id: resolve-editions
        uses: hazelcast/docker-actions/resolve-editions@master
        with:
          release-type: ${{ inputs.RELEASE_TYPE }}

      - uses: hazelcast/docker-actions/get-jfrog-credentials@master
        # Other environments use public artifacts, where credentials aren't required
        if: inputs.ENVIRONMENT == 'sandbox'
        id: jfrog
        with:
          aws-role-to-assume: ${{ secrets.AWS_HAZELCAST_OIDC_GITHUB_ACTIONS_ROLE_ARN }}
          jfrog-oidc-provider-name: ${{ github.repository_owner }}-snapshot-internal

      - name: Install dependencies
        run: |
          pip3 install -r .github/python/add-release/requirements.txt

      - name: Update metadata
        run: |
          python3 .github/python/add-release/add_release.py \
            --version=${VERSION} \
            --github-org=${GITHUB_REPOSITORY_OWNER} \
            --ee-release-repo-name=${{ vars.EE_RELEASE_REPO_NAME }} \
            --should-build-oss=${{ steps.resolve-editions.outputs.should_build_oss }} \
            --should-build-ee=${{ steps.resolve-editions.outputs.should_build_ee }}
        env:
          VERSION: ${{ inputs.VERSION }}
          RELEASE_REPO_USER: ${{ steps.jfrog.outputs.user }}
          RELEASE_REPO_TOKEN: ${{ steps.jfrog.outputs.token }}

      - uses: ./.github/actions/get-hazelcast-platform-pr-title
        id: get-pr-title
        with:
          hz-version: ${{ inputs.VERSION }}

      - name: Create PR for changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # Make a new branch from the default one
          # The default branch is the ultimate target of the PR, not the current one
          # For _typical_ workflow execution this is the same
          # But when testing changes, if running from the non-default branch (e.g. a branch with your workflow changes), the resultant version update PR will _also_ include those changes
          git checkout \
            -b "${{ github.job }}_run_${{ github.run_id }}" \
            ${{ github.event.repository.default_branch }}

          git commit \
            --all \
            --message="${{ steps.get-pr-title.outputs.title }}" \
            --message="Generated by ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}."
          git push -u origin HEAD

          gh pr create \
            --assignee "${GITHUB_ACTOR}" \
            --fill \
            --draft
        env:
          GH_TOKEN: ${{ github.token }}
