name: Promote Hazelcast platform release metadata
description: Identifies the corresponding PR for the updated release metadata from `package.yml`, updating as required and merging
run-name: ${{ github.workflow }} (`${{ inputs.VERSION }}`)

on:
  # Called from release orchestrator
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'The version to promote (e.g. `5.4.1`)'
        required: true
      RELEASE_TYPE:
        description: 'Unused, provided for compatibility with a common release promotion interface'
        required: false
        type: choice
        options:
          - ALL
          - OSS
          - EE
      ENVIRONMENT:
        description: 'Unused, provided for compatibility with a common release promotion interface'
        required: false
        type: environment
      distinct_id:
        description: 'Required exclusively for automated execution to track status of workflow execution'
        required: false

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
        # https://github.com/Codex-/return-dispatch#receiving-repository-action
      - name: Logging distinct ID (${{ inputs.distinct_id }})
        run: echo "${DISTINCT_ID}"
        env:
          DISTINCT_ID: ${{ inputs.distinct_id }}

      - name: Checkout repo
        uses: actions/checkout@v6

      - uses: ./.github/actions/get-hazelcast-platform-pr-title
        id: get-pr-title
        with:
          hz-version: ${{ inputs.VERSION }}

      - name: Find corresponding staged PR
        id: find-pr
        run: |
          source /dev/stdin <<< "$(curl --silent https://raw.githubusercontent.com/hazelcast/github-actions-common-scripts/main/logging.functions.sh)"

          PR_JSON=$(gh pr list \
            --search "'${{ steps.get-pr-title.outputs.title }}' in:title author:app/github-actions" \
            --json number,headRefName \
            --jq '.[0]')

          PR_NUMBER=$(jq -r .number <<< "${PR_JSON}")
          PR_BRANCH=$(jq -r .headRefName <<< "${PR_JSON}")

          if [[ -n "${PR_NUMBER}" || -n "${PR_BRANCH}" ]]; then
            echo "PR_NUMBER=${PR_NUMBER}" >> ${GITHUB_OUTPUT}
            echo "PR_BRANCH=${PR_BRANCH}" >> ${GITHUB_OUTPUT}
          else
            echoerr "No matching PR found to promote"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: 'Checkout PR #${{ steps.find-pr.outputs.PR_NUMBER }} (`${{ steps.find-pr.outputs.PR_BRANCH }}`)'
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.find-pr.outputs.PR_BRANCH }}

      - name: Update release date in files
        run: |
          export TBC_RELEASE_DATE=$(date +%m/%d/%Y)

          find . -type f -name "*.txt" -print0 | while IFS= read -r -d '' file; do
            envsubst < "${file}" > "${file}.tmp" && mv "${file}.tmp" "${file}"
          done

      - name: 'Commit changes to PR #${{ steps.find-pr.outputs.PR_NUMBER }}'
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git commit \
            --all \
            --message="Updating release date" \
            --message="Generated by ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}."
          git push

      - name: 'Merge PR #${{ steps.find-pr.outputs.PR_NUMBER }}'
        run: |
          gh pr ready

          gh pr merge \
            --squash
        env:
          GH_TOKEN: ${{ github.token }}
