run-name: Add Hazelcast platform release ${{ inputs.VERSION }}

on:
  # Called from release orchestrator
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'The version to release (e.g. `5.4.1`)'
        required: true
      RELEASE_TYPE:
        description: 'What should be built'
        required: true
        type: choice
        options:
          - ALL
          - OSS
          - EE
      ENVIRONMENT:
        description: 'Environment to use'
        required: true
        type: environment
      distinct_id:
        description: 'Required exclusively for automated execution to track status of workflow execution'
        required: false

jobs:
  add-release:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.VERSION }}
    steps:
        # https://github.com/Codex-/return-dispatch#receiving-repository-action
      - name: Logging distinct ID (${{ github.event.inputs.distinct_id }})
        run: echo ${{ github.event.inputs.distinct_id }}

      - uses: actions/checkout@v6

      - id: resolve-editions
        uses: hazelcast/docker-actions/resolve-editions@master
        with:
          release-type: ${{ inputs.RELEASE_TYPE }}

      - uses: hazelcast/docker-actions/get-jfrog-credentials@master
        if: inputs.ENVIRONMENT == 'sandbox'
        id: jfrog
        with:
          aws-role-to-assume: ${{ secrets.AWS_HAZELCAST_OIDC_GITHUB_ACTIONS_ROLE_ARN }}
          jfrog-oidc-provider-name: ${{ github.repository_owner }}-snapshot-internal

      - name: Install dependencies
        run: |
          pip3 install -r .github/python/add-release/requirements.txt

      - name: Update metadata
        run: |
          python3 .github/python/add-release/add_release.py \
            --version=${VERSION} \
            --github-org=${GITHUB_REPOSITORY_OWNER} \
            --ee-release-repo-name=${{ vars.EE_RELEASE_REPO_NAME }} \
            --should-build-oss=${{ steps.resolve-editions.outputs.should_build_oss }} \
            --should-build-ee=${{ steps.resolve-editions.outputs.should_build_ee }}
        env:
          RELEASE_REPO_USER: ${{ steps.jfrog.outputs.user }}
          RELEASE_REPO_TOKEN: ${{ steps.jfrog.outputs.token }}

      - name: Push back changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            
          git commit --all \
            --message="Hazelcast platform release ${VERSION}" \
            --message="Generated by ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}."
          git push
